### ISSUE TITLE
ValueError: negative seek value -9 #4

### ISSUE THREAD

**Issue by WaztWolf** [yuukawahiroshi/ddb-tools#3]
Hey im trying to Pack to DDB my samples but im getting this error
PS L:\DDB-Packer> python pack_ddb.py --src_path "L:\OpenUtau\Singers\WaztOkamineVUDEVDB\Wazt Okamine" --dst_path "L:.VOCALOID_VOICES\VoiceDB\Wazt_Okamine_V4_Beta\BM9KD8N6MLYP2MEK"
Reading DDI...
Traceback (most recent call last):
File "L:\DDB-Packer\pack_ddb.py", line 234, in
main()
File "L:\DDB-Packer\pack_ddb.py", line 79, in main
ddi_model.read()
File "L:\DDB-Packer\utils\ddi_utils.py", line 162, in read
self.ddi_data.seek(art_offset)
ValueError: negative seek value -9
i dont know if its an issue or its an error of me but i need help
![image](https://github.com/yuukawahiroshi/ddb-tools/assets/112556610/6fb8e49c-05e5-49cb-90bc-c751c7a50b52)

**Comment by peartokasane1-hash** [comment]
do you have stationary in the voicebank?

**Comment by pyramidsoftwares** [comment]
same error, i don't have stationaries in my voicebank
