### ISSUE TITLE
ValueError: negative seek value -1

### ISSUE THREAD

**Issue by multitrack-collector** [yuukawahiroshi/ddb-tools#4]
Hey, I tried to extract samples from ddb (vocaloid v3):
```
E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main>extract_wav --src_path "E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main\miku_v3_eng\MIKU_V3_English.ddb"
E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main\extract_wav.py:139: SyntaxWarning: invalid escape sequence '\^'
  center_phoneme = re.sub("^\^", "", phonemes[1])
E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main\extract_wav.py:175: SyntaxWarning: invalid escape sequence '\^'
  center_phoneme = re.sub("^\^", "", phonemes[1])
Reading DDI...
Traceback (most recent call last):
  File "E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main\extract_wav.py", line 526, in <module>
    main()
  File "E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main\extract_wav.py", line 239, in main
    ddi_model.read()
  File "E:\miku_ddb_ddi_vvd\miku_v3_english\ddb-tools-main\utils\ddi_utils.py", line 141, in read
    self.ddi_data.seek(dbv_offset)
ValueError: negative seek value -1
```

**Comment by multitrack-collector** [comment]
Oh, I think u put dd isntead of ddb lol?

**Comment by multitrack-collector** [comment]
Yes, put did file not ddb file
